### ISSUE TITLE
Sending a random fractal

### ISSUE THREAD

**Issue by alexandre** [lucasdnd/fractal-bot#12]
The bot could send a random fractal if didn't understand the message. Something like:
Me >>> "Hey bot...do you like coke?"
Bot >>> "Hmmm...I don't understand what you mean, but how about this really beatiful @#!#%@ fractal? <fractal> I used julia...".

**Comment by lucasdnd** [comment]
I already removed the parameters. The bot always sends a random fractal... I think it's much easier for people to "use".

**Comment by alexandre** [comment]
Cool. I'll try to read the code ASAP. =]
